#pragma once

/**	@file Umbrella header aggregating all concrete nodes.
 */

#include "schema/column.h"
#include "schema/table.h"
// note: though the top-level sqlite_orm.h umbrella header will include all concrete virtual tables provided by sqlite_orm
// we include it here to be independent and consistent with the other schema nodes
#include "schema/virtual_table.h"
#include "schema/view.h"
#include "schema/index.h"
#include "schema/triggers.h"
#include "schema/indexed_column.h"
#include "schema/constraints/primary_key.h"
#include "schema/constraints/foreign_key.h"
#include "schema/constraints/null.h"
#include "schema/constraints/unique.h"
#include "schema/constraints/default.h"
#include "schema/constraints/check.h"
#include "schema/constraints/generated_always.h"
#include "schema/constraints/auxiliary.h"
#include "schema/constraints/prefix.h"
#include "schema/constraints/tokenize.h"
#include "schema/constraints/content.h"
#include "schema/constraints/unindexed.h"
#include "schema/constraints/collate.h"

#include "ast/quoted_expression.h"
#include "ast/between.h"
#include "ast/case_expression.h"
#include "ast/cast.h"
#include "ast/compound_operator.h"
#include "ast/cross_join.h"
#include "ast/cte.h"
#include "ast/dml/default_values.h"
#include "ast/dml/insert.h"
#include "ast/dml/into.h"
#include "ast/dml/replace.h"
#include "ast/dml/set.h"
#include "ast/dml/update.h"
#include "ast/dml/remove.h"
#include "ast/dml/upsert_clause.h"
#include "ast/excluded.h"
#include "ast/exists.h"
#include "ast/fts5_functions.h"
#include "ast/group_by.h"
#include "ast/in.h"
#include "ast/is_not_null.h"
#include "ast/is_null.h"
#include "ast/limit.h"
#include "ast/match.h"
#include "ast/offset.h"
#include "ast/rank.h"
#include "ast/result_columns.h"
#include "ast/rowset_deduplicators.h"
#include "ast/select.h"
#include "ast/special_keywords.h"
#include "ast/values.h"
#include "ast/where.h"
#include "ast/window.h"
